# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import vad_pb2 as proto_dot_vad__pb2


class VoiceActivityDetectorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.detect_voice_activity = channel.unary_unary(
                '/VoiceActivityDetector/detect_voice_activity',
                request_serializer=proto_dot_vad__pb2.VoiceActivityDetectorRequest.SerializeToString,
                response_deserializer=proto_dot_vad__pb2.VoiceActivityDetectorResponse.FromString,
                )


class VoiceActivityDetectorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def detect_voice_activity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VoiceActivityDetectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'detect_voice_activity': grpc.unary_unary_rpc_method_handler(
                    servicer.detect_voice_activity,
                    request_deserializer=proto_dot_vad__pb2.VoiceActivityDetectorRequest.FromString,
                    response_serializer=proto_dot_vad__pb2.VoiceActivityDetectorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'VoiceActivityDetector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VoiceActivityDetector(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def detect_voice_activity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/VoiceActivityDetector/detect_voice_activity',
            proto_dot_vad__pb2.VoiceActivityDetectorRequest.SerializeToString,
            proto_dot_vad__pb2.VoiceActivityDetectorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
