# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/vad.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fproto/vad.proto\"2\n\x1cVoiceActivityDetectorRequest\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\"3\n\x1dVoiceActivityDetectorResponse\x12\x12\n\nconfidence\x18\x01 \x01(\x02\x32q\n\x15VoiceActivityDetector\x12X\n\x15\x64\x65tect_voice_activity\x12\x1d.VoiceActivityDetectorRequest\x1a\x1e.VoiceActivityDetectorResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.vad_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VOICEACTIVITYDETECTORREQUEST']._serialized_start=19
  _globals['_VOICEACTIVITYDETECTORREQUEST']._serialized_end=69
  _globals['_VOICEACTIVITYDETECTORRESPONSE']._serialized_start=71
  _globals['_VOICEACTIVITYDETECTORRESPONSE']._serialized_end=122
  _globals['_VOICEACTIVITYDETECTOR']._serialized_start=124
  _globals['_VOICEACTIVITYDETECTOR']._serialized_end=237
# @@protoc_insertion_point(module_scope)
